version: '3.1'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka1:
    container_name: 'kafka1'
    image: 'bitnami/kafka:latest'
    ports:
      - '9093:9093'
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=11
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=INT://:9092,EXT://0.0.0.0:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INT:PLAINTEXT,EXT:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INT
      - KAFKA_CFG_ADVERTISED_LISTENERS=INT://:9092,EXT://localhost:9093
#  kafka2:
#    container_name: 'kafka2'
#    image: 'bitnami/kafka:latest'
#    ports:
#      - '9094:9094'
#    depends_on:
#      - zookeeper
#    environment:
#      - KAFKA_BROKER_ID=22
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#      - ALLOW_PLAINTEXT_LISTENER=yes
#      - KAFKA_CFG_LISTENERS=INT://:9092,EXT://0.0.0.0:9094
#      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INT:PLAINTEXT,EXT:PLAINTEXT
#      - KAFKA_INTER_BROKER_LISTENER_NAME=INT
#      - KAFKA_CFG_ADVERTISED_LISTENERS=INT://:9092,EXT://localhost:9094